language: "en-US"
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Do Not Merge"
    drafts: false
    base_branches: ["master"]
tools:
  spellcheck:
    enabled: true
  markdownlint:
    enabled: true
  biome:
    enabled: true
chat:
  auto_reply: true
